### ISSUE TITLE
Crash during migration

### ISSUE THREAD

**Issue by yangsuo1991** [kryojenik/miniloader-migration#1]
Hi Kryojenik,

Thank you so much for continuing the miniloader in 2.0. I have a big Pyanodons save with maybe more than 10k miniloader entities that failed to migrate with this mod and it crashes with the following error. Could you help us take a look? Thanks again!

The mod Modernized Miniloader Migration (1.0.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event miniloader-migration::on_gui_click (ID 1)
Index out of bounds: 4
stack traceback:
	[C]: in function 'create_entity'
	__miniloader-migration__/scripts/from-miniloader.lua:113: in function 'replace_miniloader'
	__miniloader-migration__/scripts/from-miniloader.lua:490: in function 'handler'
	__flib__/gui.lua:177: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

You can find the save file here:
https://drive.google.com/file/d/1hNSS3NVG9JMWf3oiWkRz2Mdsdz-7XWed/view?usp=sharing

**Comment by kryojenik** [comment]
Thanks for the report and the save file.   I believe this one is squished.

**Comment by yangsuo1991** [comment]
I migrated successfully after the update. Thank you so much and happy holidays!
